name: kodress
description: The kodress Dart package provides a user-friendly
  UI component for seamlessly integrating Korean street address 
  searching into your Dart and Flutter applications. 
version: 0.1.1+2
repository: https://github.com/soliev01/kodress


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
